# Stage 1: Build the Go application
FROM golang:1.20 AS builder
WORKDIR /app
COPY . .
RUN go build -o date-time-server .

# Stage 2: Create a small runtime image
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/date-time-server .
EXPOSE 8080
CMD ["./date-time-server"]
