# Stage 1: Build the Go application
FROM golang:1.20 AS builder
WORKDIR /app
COPY . .
RUN go build -o date-time-server .

# Stage 2: Create a small runtime image
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/date-time-server .
EXPOSE 8080
CMD ["./date-time-server"]
apiVersion: apps/v1
kind: Deployment
metadata:
  name: date-time-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: date-time-server
  template:
    metadata:
      labels:
        app: date-time-server
    spec:
      containers:
      - name: date-time-server
        image: <your-dockerhub-username>/my-date-time-server:latest
        ports:
        - containerPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: date-time-server-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: date-time-server
